"use client"
import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { AuthProvider } from './contexts/authContext';

export const metadata = {
  title: 'eLearning',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          <AntdRegistry>{children}</AntdRegistry>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  )
}
